In [ ]:
import pandas as pd

In [ ]:
data=pd.read_csv("hotel_bookings_cleaned.csv")

In [ ]:
df=pd.DataFrame(data)

In [12]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,total_nights,is_family
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01,0,0
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01,0,0
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02,1,0
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02,1,0
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03,2,0

In [13]:
df.tail()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,total_nights,is_family
115591,City Hotel,0,21,2017,August,35,30,2,5,2,...,NaN,0,Transient,96.14,0,2,Check-Out,2017-09-06,7,0
115592,City Hotel,0,23,2017,August,35,30,2,5,2,...,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06,7,0
115593,City Hotel,0,34,2017,August,35,31,2,5,2,...,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07,7,0
115594,City Hotel,0,109,2017,August,35,31,2,5,2,...,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07,7,0
115595,City Hotel,0,205,2017,August,35,29,2,7,2,...,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07,9,0

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 115596 entries, 0 to 115595
Data columns (total 34 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           115596 non-null  str
 1   is_canceled                     115596 non-null  int64
 2   lead_time                       115596 non-null  int64
 3   arrival_date_year               115596 non-null  int64
 4   arrival_date_month              115596 non-null  str
 5   arrival_date_week_number        115596 non-null  int64
 6   arrival_date_day_of_month       115596 non-null  int64
 7   stays_in_weekend_nights         115596 non-null  int64
 8   stays_in_week_nights            115596 non-null  int64
 9   adults                          115596 non-null  int64
 10  children                        115592 non-null  float64
 11  babies                          115596 non-null  int64
 12  meal                            115596 non-null  str
 13  country                         115116 non-null  str
 14  market_segment                  115596 non-null  str
 15  distribution_channel            115596 non-null  str
 16  is_repeated_guest               115596 non-null  int64
 17  previous_cancellations          115596 non-null  int64
 18  previous_bookings_not_canceled  115596 non-null  int64
 19  reserved_room_type              115596 non-null  str
 20  assigned_room_type              115596 non-null  str
 21  booking_changes                 115596 non-null  int64
 22  deposit_type                    115596 non-null  str
 23  agent                           99620 non-null   float64
 24  company                         6785 non-null    float64
 25  days_in_waiting_list            115596 non-null  int64
 26  customer_type                   115596 non-null  str
 27  adr                             115596 non-null  float64
 28  required_car_parking_spaces     115596 non-null  int64
 29  total_of_special_requests       115596 non-null  int64
 30  reservation_status              115596 non-null  str
 31  reservation_status_date         115596 non-null  str
 32  total_nights                    115596 non-null  int64
 33  is_family                       115596 non-null  int64
dtypes: float64(4), int64(18), str(12)
memory usage: 38.5 MB

In [15]:
df.describe()

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,...,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests,total_nights,is_family
count,115596.000000,115596.000000,115596.000000,115596.000000,115596.000000,115596.000000,115596.000000,115596.000000,115592.000000,115596.000000,...,115596.000000,115596.000000,99620.000000,6785.000000,115596.000000,115596.000000,115596.000000,115596.000000,115596.000000,115596.000000
mean,0.369866,105.018816,2016.144745,27.045936,15.770182,0.920741,2.481435,1.846033,0.082679,0.007492,...,0.140809,0.216988,84.096396,189.153574,2.387660,97.037538,0.059673,0.561680,3.402177,0.065962
std,0.482770,107.699052,0.706988,13.751489,8.783452,0.997622,1.905854,0.579325,0.349962,0.095103,...,1.521071,0.647182,109.802845,131.462787,17.863897,40.613593,0.240110,0.785334,2.552645,0.248218
min,0.000000,0.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,18.000000,2016.000000,16.000000,8.000000,0.000000,1.000000,2.000000,0.000000,0.000000,...,0.000000,0.000000,9.000000,62.000000,0.000000,68.000000,0.000000,0.000000,2.000000,0.000000
50%,0.000000,70.000000,2016.000000,27.000000,16.000000,1.000000,2.000000,2.000000,0.000000,0.000000,...,0.000000,0.000000,14.000000,178.000000,0.000000,92.000000,0.000000,0.000000,3.000000,0.000000
75%,1.000000,162.000000,2017.000000,38.000000,23.000000,2.000000,3.000000,2.000000,0.000000,0.000000,...,0.000000,0.000000,193.000000,270.000000,0.000000,121.370000,0.000000,1.000000,4.000000,0.000000
max,1.000000,737.000000,2017.000000,53.000000,31.000000,19.000000,50.000000,55.000000,10.000000,10.000000,...,72.000000,21.000000,535.000000,543.000000,391.000000,211.030000,8.000000,5.000000,69.000000,1.000000

In [25]:
a=df['arrival_date_week_number']
a.mean()
a.mode()
a.min()
a.max()
a.std()
a.sum()
a.count()
a.median()

np.float64(27.0)